# Generated by Django 5.1.3 on 2025-10-04 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='batch_code',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='is_active',
        ),
    ]
